export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const FETCH_CHARACTER_BY_ID = "FETCH_CHARACTER_BY_ID";
export const FETCH_EPISODES = "FETCH_EPISODES";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const FETCH_FAVORITES = "FETCH_FAVORITES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_TO_FAVORITES = "REMOVE_TO_FAVORITES";
export const SET_ISLOADING = "SET_ISLOADING";
